In [1]:
'''
Container squences:
  list, tuple, collections.deque 可以保存不同类型的item
Flat squences:
  str, bytes, bytearray, memoryview, array.array 保存一种类型
Mutable squences:
  list, bytearray, array.array, collections.deque, memoryview 可变
Immutable squences: 
  tuple, str, bytes 不可变
'''
symbols = '@#$%^&'  #string

In [2]:
codes = []  #list

In [3]:
for symbol in symbols:
    codes.append(ord(symbol))

In [4]:
codes

[64, 35, 36, 37, 94, 38]

In [5]:
#List comprehensions and readability
codes = [ord(symbol) for symbol in symbols]

In [6]:
codes

[64, 35, 36, 37, 94, 38]

In [7]:
x = 'ABC'

In [8]:
dummy = [ord(x) for x in x]  #验证x的local scope

In [9]:
x

'ABC'

In [10]:
dummy

[65, 66, 67]

In [15]:
beyond_ascii = [ord(s) for s in symbols if ord(s) > 63]  #List comprehensions method

In [16]:
beyond_ascii

[64, 94]

In [19]:
beyond_ascii = list(filter(lambda c:c > 63, map(ord, symbols)))  #map/filter composition method 

In [20]:
beyond_ascii

[64, 94]

In [26]:
colors = ['black', 'white']

In [27]:
sizes = ['S', 'M', 'L', 'XL']

In [30]:
# Generates a list of tuples arranged by color, then size
tshirts = [(color, size) for color in colors for size in sizes]

In [31]:
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('black', 'XL'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L'),
 ('white', 'XL')]

In [32]:
type(tshirts)

list

In [34]:
for color in colors:
    for size in sizes:
        print ((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('black', 'XL')
('white', 'S')
('white', 'M')
('white', 'L')
('white', 'XL')


Generator Expressions, Genexps

In [35]:
tuple(ord(symbol) for symbol in symbols)

(64, 35, 36, 37, 94, 38)

In [37]:
import array
array.array('I', (ord(symbol) for symbol in symbols))  #array.array: 'I' unsigned int 

array('I', [64, 35, 36, 37, 94, 38])

In [39]:
for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
black XL
white S
white M
white L
white XL


Tuple uesd as records

In [41]:
lax_coordinates = (33.9425, -118.408056)

In [42]:
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)  #tuple unpacking

In [43]:
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

In [44]:
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)  #tuple unpacking

BRA/CE342567
ESP/XDA205856
USA/31195855


In [45]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


tuple unpacking

In [47]:
a, b = 1, 2  #tuple unpacking, swapping the values of variables without using a temporary variable
a, b = b, a
print(a, b)

2 1


In [50]:
divmod(20, 8)

(2, 4)

In [53]:
t = (20, 8)
divmod(*t) #tuple unpack, prefixing an argument with a star when calling a function

(2, 4)

In [55]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [56]:
import os
_, filename = os.path.split('/Users/linheng/.ssh/id_rsa.pub')  #return a tuple (path, last_part), _ is used as dummy variable
filename

'id_rsa.pub'

In [58]:
a, b, *rest = range(5)  #using *args to grab excess items, which is a classic Python feature
a, b, rest

(0, 1, [2, 3, 4])

In [59]:
a, *body, b, c = range(5)  #It can place any postition
a, body, b, c

(0, [1, 2], 3, 4)

In [60]:
*body, a, b, c = range(5)
body, a, b, c

([0, 1], 2, 3, 4)

Nested tuple unpacking

In [1]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('San Paula', 'BR', 19.649, (-23.547778, -46.635833))
]
print('{:15} | {:^9} | {:9}'.format('city', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

city            |   lat.    | long.    
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
San Paula       |  -23.5478 |  -46.6358


Named tuples

In [11]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [12]:
tokyo.population

36.933

In [13]:
tokyo.coordinates

(35.689722, 139.691667)

In [14]:
tokyo[0]

'Tokyo'

In [17]:
tokyo._fields

('name', 'country', 'population', 'coordinates')

In [19]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
delhi._asdict()

OrderedDict([('name', 'Delhi NCR'),
             ('country', 'IN'),
             ('population', 21.935),
             ('coordinates', LatLong(lat=28.613889, long=77.208889))])

In [26]:
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


Slice Object

In [27]:
s = 'bicycle'
s[::3]   #s[a:b:c] step c

'bye'

In [28]:
s[::-1]

'elcycib'

In [29]:
s[::-2]

'eccb'

In [36]:
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                     $17.50    3    $52.50
1489  6mm Tactile Switch x20                 $4.95    2     $9.90
1510  Panavise Jr. - PV-201                 $28.00    1    $28.00
1601  PiTFT Mini Kit 320x240                $34.95    1 .  $34.95
"""
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

    $17.50   Pimoroni PiBrella .               
     $4.95   6mm Tactile Switch x20            
    $28.00   Panavise Jr. - PV-201             
    $34.95   PiTFT Mini Kit 320x240            
 


In [59]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [61]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [62]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [63]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [64]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [65]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

Building lists of lists

In [67]:
#a Tic-tac-toe board
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [68]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [2]:
#wrong shortcut, rows are referring to the same object.
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [3]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [4]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [5]:
t

(1, 2, [30, 40, 50, 60])

In [7]:
import dis  #bytecode for s[a] += b
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


list.sort and sorted built-in function

In [8]:
#sorted create a new list and returns it.
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [9]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [10]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [11]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [12]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [13]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

Searching with bisect

In [4]:
import bisect
import sys
HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]
ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))

if __name__ == "__main__":
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

print('DEMO', bisect_fn.__name__)
print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
demo(bisect_fn)

DEMO bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [7]:
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

inserting with bisect.insort

In [9]:
import bisect
import random
SIZE = 7
my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)
    

12 -> [12]
 5 -> [5, 12]
 6 -> [5, 6, 12]
 4 -> [4, 5, 6, 12]
10 -> [4, 5, 6, 10, 12]
 3 -> [3, 4, 5, 6, 10, 12]
 8 -> [3, 4, 5, 6, 8, 10, 12]


Arrays

In [34]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**6)))
floats[-1]

0.862480737656495

In [35]:
len(floats)

1000000

In [39]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()
floats2 = array('d')  #typecode 'd', double-precision, create an empty array of doubles
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**6)  #read 10 million numbers from the binary file
fp.close()
floats2[-1]  #inspect the last number in the array

0.862480737656495

In [40]:
floats2 == floats  #verify that the contents of the arrays match

True

Memory views

In [15]:
numbers = array('h', [-2, -1, 0, 1, 2])  #typecode 'h', short signed integers
memv = memoryview(numbers)  
len(memv)

5

In [16]:
memv[0]

-2

In [17]:
memv_oct = memv.cast('B')  #typecode 'B', unsigned char
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [21]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

Numpy and SciPy

In [22]:
import numpy as np

In [23]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
type(a)

numpy.ndarray

In [25]:
a.shape

(12,)

In [26]:
a.shape = 3, 4  #change the shape

In [27]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a[2]  #get row

array([ 8,  9, 10, 11])

In [29]:
a[2, 1]  #get element

9

In [30]:
a[:, 1]  #get column

array([1, 5, 9])

In [31]:
a[1, :]

array([4, 5, 6, 7])

In [32]:
a.transpose()  #create a new array by transposing(swapping columns with rows)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Deque and other queues
>  The deque(collections.deque) is a thread-safe double-ended queue designed for fast inserting and removing from both ends.

In [41]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
dq.rotate(-3)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [49]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
dq.extend([11, 22, 33])
dq

deque([6, 7, 8, 9, 11, 22, 33, 11, 22, 33])

In [58]:
dq1 = deque(range(12))
dq1.appendleft(1)
dq1

deque([1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])