## Numpy Arrays

In [3]:
import numpy as np
a = np.arange(5)
a.dtype

dtype('int64')

In [4]:
a

array([0, 1, 2, 3, 4])

In [5]:
a.shape

(5,)

In [8]:
# Create a multidimensional array
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [9]:
m.shape

(2, 2)

In [10]:
m.dtype

dtype('int64')

In [14]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [15]:
a[0, 1]

2

In [16]:
m.dtype.itemsize

8